@extends('layouts.customer')
@section('content')
<div class="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8 lg:py-12">
    <div class="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-[.18em] text-[#c08246]">Checkout</p><h1 class="text-3xl font-black text-stone-900">Keranjang Belanja</h1></div><a href="{{ route('home') }}" class="text-sm font-bold text-stone-500 hover:text-stone-900">← Lanjut belanja</a></div>
    @if(count($cart))
        @php($total = collect($cart)->sum(fn($item)=>$item['price']*$item['quantity']))
        <div class="mt-7 grid gap-6 lg:grid-cols-[1.2fr_.8fr] lg:items-start">
            <div class="space-y-3">
                @foreach($cart as $id=>$item)
                <div class="sk-card flex flex-col gap-4 p-4 sm:flex-row sm:items-center"><img src="{{ $item['image'] }}" class="h-24 w-full rounded-2xl object-cover sm:h-24 sm:w-24" alt="{{ $item['name'] }}"><div class="min-w-0 flex-1"><p class="font-black text-stone-900">{{ $item['name'] }}</p><p class="mt-1 text-sm text-stone-500">Rp {{ number_format($item['price'],0,',','.') }}</p><div class="mt-3 flex flex-wrap items-center gap-2"><form action="{{ route('cart.update',$id) }}" method="POST" class="flex items-center gap-2">@csrf @method('PATCH')<input class="w-20 rounded-xl border-stone-200 px-3 py-2 text-sm" type="number" name="quantity" min="1" max="20" value="{{ $item['quantity'] }}"><button class="sk-btn-soft py-2 text-xs">Update</button></form><form action="{{ route('cart.remove',$id) }}" method="POST">@csrf @method('DELETE')<button class="rounded-xl px-3 py-2 text-xs font-bold text-red-600 hover:bg-red-50">Hapus</button></form></div></div><p class="text-lg font-black text-stone-900">Rp {{ number_format($item['price']*$item['quantity'],0,',','.') }}</p></div>
                @endforeach
            </div>
            <form action="{{ route('checkout') }}" method="POST" class="sk-card p-5 sm:p-6 lg:sticky lg:top-24">@csrf<h2 class="text-lg font-black text-stone-900">Ringkasan Pesanan</h2><div class="mt-5 flex items-center justify-between text-sm"><span class="text-stone-500">Subtotal</span><span class="font-bold">Rp {{ number_format($total,0,',','.') }}</span></div><div class="mt-2 flex items-center justify-between text-sm"><span class="text-stone-500">Biaya layanan</span><span class="font-bold">Gratis</span></div><div class="my-5 border-t border-stone-200"></div><div class="flex items-end justify-between gap-4"><div><p class="text-xs text-stone-500">Total</p><p class="text-2xl font-black text-[#c08246]">Rp {{ number_format($total,0,',','.') }}</p></div></div><div class="mt-6"><label class="mb-2 block text-sm font-bold">Metode pembayaran</label><div class="grid grid-cols-1 gap-2 sm:grid-cols-3 lg:grid-cols-1"><label class="cursor-pointer"><input required type="radio" name="payment_method" value="qris" class="peer sr-only"><span class="block rounded-xl border border-stone-200 p-3 text-sm font-bold peer-checked:border-[#c08246] peer-checked:bg-[#fff7ef]">QRIS</span></label><label class="cursor-pointer"><input type="radio" name="payment_method" value="cash" class="peer sr-only"><span class="block rounded-xl border border-stone-200 p-3 text-sm font-bold peer-checked:border-[#c08246] peer-checked:bg-[#fff7ef]">Cash</span></label><label class="cursor-pointer"><input type="radio" name="payment_method" value="transfer" class="peer sr-only"><span class="block rounded-xl border border-stone-200 p-3 text-sm font-bold peer-checked:border-[#c08246] peer-checked:bg-[#fff7ef]">Transfer</span></label></div></div><button class="sk-btn-primary mt-6 w-full py-3">Buat Pesanan</button><p class="mt-3 text-center text-xs text-stone-400">Status pesanan dapat dipantau setelah checkout.</p></form>
        </div>
    @else
        <div class="mt-8 rounded-3xl border border-dashed border-stone-300 bg-white px-5 py-20 text-center"><div class="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-[#f6ede5] text-[#7a4b2d]"><svg class="h-8 w-8" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-width="1.8" d="M3 4h2l1.6 10.2a2 2 0 0 0 2 1.7h7.9a2 2 0 0 0 2-1.7L20 8H7M10 20a1 1 0 1 1-2 0 1 1 0 0 1 2 0Zm8 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0Z"/></svg></div><h2 class="mt-4 text-xl font-black">Keranjangmu masih kosong</h2><p class="mt-2 text-sm text-stone-500">Yuk pilih kopi atau camilan favoritmu.</p><a href="{{ route('home') }}" class="sk-btn-primary mt-5">Lihat Menu</a></div>
    @endif
</div>
@endsection
